# Generated by Django 5.1 on 2024-08-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='business',
            field=models.CharField(default='kingship', max_length=255),
        ),
    ]
