# Generated by Django 5.1 on 2024-08-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='business',
            new_name='supplier',
        ),
    ]
